export const SUCCESS_GET_CONTACT_DATA = 'HOME/SUCCESS_GET_CONTACT_DATA'
export const FAILURE_GET_CONTACT_DATA = 'HOME/FAILURE_GET_CONTACT_DATA'

export const SUCCESS_SEND_CONTACT = 'HOME/SUCCESS_SEND_CONTACT'
export const FAILURE_SEND_CONTACT = 'HOME/FAILURE_SEND_CONTACT'
