export const SUCCESS_GET_LIST_GALLERY_DATA = 'HOME/SUCCESS_GET_LIST_GALLERY_DATA'
export const FAILURE_GET_LIST_GALLERY_DATA = 'HOME/FAILURE_GET_LIST_GALLERY_DATA'
export const SUCCESS_GET_MORE_LIST_GALLERY_DATA = 'HOME/SUCCESS_GET_MORE_LIST_GALLERY_DATA'
export const FAILURE_GET_MORE_LIST_GALLERY_DATA = 'HOME/FAILURE_GET_MORE_LIST_GALLERY_DATA'
export const SUCCESS_EMPTY_LIST_GALLERY_DATA = 'HOME/SUCCESS_EMPTY_LIST_GALLERY_DATA'
// export const FAILURE_EMPTY_LIST_GALLERY_DATA = 'HOME/FAILURE_EMPTY_LIST_GALLERY_DATA'

export const SUCCESS_GET_GALLERY_DATA = 'HOME/SUCCESS_GET_GALLERY_DATA'
export const FAILURE_GET_GALLERY_DATA = 'HOME/FAILURE_GET_GALLERY_DATA'
