export default {
  Roboto: {
    black: 'Roboto-Black',
    blackitalic: 'Roboto-BlackItalic',
    bold: 'Roboto-Bold',
    bolditalic: 'Roboto-BoldItalic',
    // extrabold: 'Roboto-ExtraBold',
    // extrabolditalic: 'Roboto-ExtraBoldItalic',
    // extralight: 'Roboto-ExtraLight',
    // extralightitalic: 'Roboto-ExtraLightItalic',
    light: 'Roboto-Light',
    lightitalic: 'Roboto-LightItalic',
    medium: 'Roboto-Medium',
    mediumitalic: 'Roboto-MediumItalic',
    regular: 'Roboto-Regular',
    regularitalic: 'Roboto-RegularItalic',
    // semibold: 'Roboto-SemiBold',
    // semibolditalic: 'Roboto-SemiBoldItalic',
    thin: 'Roboto-Thin',
    thinitalic: 'Roboto-ThinItalic',
  },
  WorkSans: {
    black: 'WorkSans-Black',
    // blackitalic: 'WorkSans-BlackItalic',
    bold: 'WorkSans-Bold',
    // bolditalic: 'WorkSans-BoldItalic',
    extrabold: 'WorkSans-ExtraBold',
    // extrabolditalic: 'WorkSans-ExtraBoldItalic',
    extralight: 'WorkSans-ExtraLight',
    // extralightitalic: 'WorkSans-ExtraLightItalic',
    light: 'WorkSans-Light',
    // lightitalic: 'WorkSans-LightItalic',
    medium: 'WorkSans-Medium',
    // mediumitalic: 'WorkSans-MediumItalic',
    regular: 'WorkSans-Regular',
    // regularitalic: 'WorkSans-RegularItalic',
    semibold: 'WorkSans-SemiBold',
    // semibolditalic: 'WorkSans-SemiBoldItalic',
    thin: 'WorkSans-Thin',
    // thinitalic: 'WorkSans-ThinItalic',
  },
}
