export const SUCCESS_GET_FOOTER_DATA = 'GLOBAL/SUCCESS_GET_FOOTER_DATA'
export const FAILURE_GET_FOOTER_DATA = 'GLOBAL/FAILURE_GET_FOOTER_DATA'

export const SUCCESS_POST_SUBSCRIBER_DATA = 'GLOBAL/SUCCESS_POST_SUBSCRIBER_DATA'
export const FAILURE_POST_SUBSCRIBER_DATA = 'GLOBAL/FAILURE_POST_SUBSCRIBER_DATA'
